#!/bin/bash
cd "${0%/*}"
cd 'Minecraft-Alpha-Server'
git -c user.name='stonar96' -c user.email='minecraft.stonar96@gmail.com' am --committer-date-is-author-date --ignore-whitespace '../Patches/'*'.patch'
sed 's/^M$//' 'cleanup.sh' > 'cleanup1.sh'
sed 's/^M$//' 'decompile.sh' > 'decompile1.sh'
sed 's/^M$//' 'recompile.sh' > 'recompile1.sh'
sed 's/^M$//' 'reobf.sh' > 'reobf1.sh'
sed 's/^M$//' 'setup.sh' > 'setup1.sh'
sed 's/^M$//' 'test_game.sh' > 'test_game1.sh'
sed 's/^M$//' 'test_server.sh' > 'test_server1.sh'
sed 's/^M$//' 'update_names.sh' > 'update_names1.sh'
rm -f 'cleanup.sh'
rm -f 'decompile.sh'
rm -f 'recompile.sh'
rm -f 'reobf.sh'
rm -f 'setup.sh'
rm -f 'test_game.sh'
rm -f 'test_server.sh'
rm -f 'update_names.sh'
mv 'cleanup1.sh' 'cleanup.sh'
mv 'decompile1.sh' 'decompile.sh'
mv 'recompile1.sh' 'recompile.sh'
mv 'reobf1.sh' 'reobf.sh'
mv 'setup1.sh' 'setup.sh'
mv 'test_game1.sh' 'test_game.sh'
mv 'test_server1.sh' 'test_server.sh'
mv 'update_names1.sh' 'update_names.sh'
case "$(uname -s)" in
  MINGW*|CYGWIN*)
    git update-index --add --chmod='+x' 'cleanup.sh'
    git update-index --add --chmod='+x' 'decompile.sh'
    git update-index --add --chmod='+x' 'recompile.sh'
    git update-index --add --chmod='+x' 'reobf.sh'
    git update-index --add --chmod='+x' 'setup.sh'
    git update-index --add --chmod='+x' 'test_game.sh'
    git update-index --add --chmod='+x' 'test_server.sh'
    git update-index --add --chmod='+x' 'update_names.sh'
    ;;
  *)
    chmod +x 'cleanup.sh'
    chmod +x 'decompile.sh'
    chmod +x 'recompile.sh'
    chmod +x 'reobf.sh'
    chmod +x 'setup.sh'
    chmod +x 'test_game.sh'
    chmod +x 'test_server.sh'
    chmod +x 'update_names.sh'
    ;;
esac
git add '.'
